package pojos;
// Generated 1/12/2016 09:36:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeType generated by hbm2java
 */
public class EmployeeType  implements java.io.Serializable {


     private int idEmployeeType;
     private String employeeType;
     private Set tusers = new HashSet(0);

    public EmployeeType() {
    }

	
    public EmployeeType(int idEmployeeType) {
        this.idEmployeeType = idEmployeeType;
    }
    public EmployeeType(int idEmployeeType, String employeeType, Set tusers) {
       this.idEmployeeType = idEmployeeType;
       this.employeeType = employeeType;
       this.tusers = tusers;
    }
   
    public int getIdEmployeeType() {
        return this.idEmployeeType;
    }
    
    public void setIdEmployeeType(int idEmployeeType) {
        this.idEmployeeType = idEmployeeType;
    }
    public String getEmployeeType() {
        return this.employeeType;
    }
    
    public void setEmployeeType(String employeeType) {
        this.employeeType = employeeType;
    }
    public Set getTusers() {
        return this.tusers;
    }
    
    public void setTusers(Set tusers) {
        this.tusers = tusers;
    }




}


