package pojos;
// Generated 21/11/2016 03:58:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EventType generated by hbm2java
 */
public class EventType  implements java.io.Serializable {


     private int idEventType;
     private String eventType;
     private Set teventses = new HashSet(0);

    public EventType() {
    }

	
    public EventType(int idEventType) {
        this.idEventType = idEventType;
    }
    public EventType(int idEventType, String eventType, Set teventses) {
       this.idEventType = idEventType;
       this.eventType = eventType;
       this.teventses = teventses;
    }
   
    public int getIdEventType() {
        return this.idEventType;
    }
    
    public void setIdEventType(int idEventType) {
        this.idEventType = idEventType;
    }
    public String getEventType() {
        return this.eventType;
    }
    
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }
    public Set getTeventses() {
        return this.teventses;
    }
    
    public void setTeventses(Set teventses) {
        this.teventses = teventses;
    }




}


