package pojos;
// Generated 1/12/2016 09:36:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tevents generated by hbm2java
 */
public class Tevents  implements java.io.Serializable {


     private Integer idevent;
     private EventType eventType;
     private Tuser tuser;
     private String description;
     private Date date;
     private Set ttransfers = new HashSet(0);

    public Tevents() {
    }

    public Tevents(EventType eventType, Tuser tuser, String description, Date date, Set ttransfers) {
       this.eventType = eventType;
       this.tuser = tuser;
       this.description = description;
       this.date = date;
       this.ttransfers = ttransfers;
    }
   
    public Integer getIdevent() {
        return this.idevent;
    }
    
    public void setIdevent(Integer idevent) {
        this.idevent = idevent;
    }
    public EventType getEventType() {
        return this.eventType;
    }
    
    public void setEventType(EventType eventType) {
        this.eventType = eventType;
    }
    public Tuser getTuser() {
        return this.tuser;
    }
    
    public void setTuser(Tuser tuser) {
        this.tuser = tuser;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getTtransfers() {
        return this.ttransfers;
    }
    
    public void setTtransfers(Set ttransfers) {
        this.ttransfers = ttransfers;
    }




}


