package pojos;
// Generated 1/12/2016 09:36:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tproducts generated by hbm2java
 */
public class Tproducts  implements java.io.Serializable {


     private Integer productId;
     private String codebar;
     private String productName;
     private Integer cost;
     private String description;
     private Integer existence;
     private Set ttransfers = new HashSet(0);

    public Tproducts() {
    }

    public Tproducts(String codebar, String productName, Integer cost, String description, Integer existence, Set ttransfers) {
       this.codebar = codebar;
       this.productName = productName;
       this.cost = cost;
       this.description = description;
       this.existence = existence;
       this.ttransfers = ttransfers;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getCodebar() {
        return this.codebar;
    }
    
    public void setCodebar(String codebar) {
        this.codebar = codebar;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Integer getCost() {
        return this.cost;
    }
    
    public void setCost(Integer cost) {
        this.cost = cost;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getExistence() {
        return this.existence;
    }
    
    public void setExistence(Integer existence) {
        this.existence = existence;
    }
    public Set getTtransfers() {
        return this.ttransfers;
    }
    
    public void setTtransfers(Set ttransfers) {
        this.ttransfers = ttransfers;
    }




}


