package pojos;
// Generated 1/12/2016 09:36:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tuser generated by hbm2java
 */
public class Tuser  implements java.io.Serializable {


     private String iduser;
     private EmployeeType employeeType;
     private String firstName;
     private String lastName;
     private String password;
     private Set teventses = new HashSet(0);

    public Tuser() {
    }

	
    public Tuser(String iduser) {
        this.iduser = iduser;
    }
    public Tuser(String iduser, EmployeeType employeeType, String firstName, String lastName, String password, Set teventses) {
       this.iduser = iduser;
       this.employeeType = employeeType;
       this.firstName = firstName;
       this.lastName = lastName;
       this.password = password;
       this.teventses = teventses;
    }
   
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }
    public EmployeeType getEmployeeType() {
        return this.employeeType;
    }
    
    public void setEmployeeType(EmployeeType employeeType) {
        this.employeeType = employeeType;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getTeventses() {
        return this.teventses;
    }
    
    public void setTeventses(Set teventses) {
        this.teventses = teventses;
    }




}


